table f_roomnights
	lineageTag: e8e6dd3c-0a40-4301-bdb2-3f3656f859e4
	sourceLineageTag: [dbo].[f_roomnights]

	/// Count of room-night rows in f_roomnights. Grain verified as one row per reservation per stay date. Currently includes day-use rows; inclusion policy for the headline metric is not yet governed.
	measure 'Room Nights' = COUNTROWS ( f_roomnights )
		formatString: #,##0
		displayFolder: 01 Volume
		lineageTag: 98cea3e5-536a-4aee-9698-04eb57be3961

	/// Distinct reservations present in the current filter context. A multi-night stay counts once.
	measure Reservations = DISTINCTCOUNT ( f_roomnights[ReservationID] )
		formatString: #,##0
		displayFolder: 01 Volume
		lineageTag: 8d363ce5-0a57-4760-bb03-c4a51a0cc568

	/// Room nights excluding day-use rows. Day-use handling governed under D-206.
	measure 'Overnight Room Nights' = CALCULATE ( [Room Nights], f_roomnights[IsDayUse] = FALSE () )
		formatString: #,##0
		displayFolder: 01 Volume
		lineageTag: 67ab5200-6a29-4e5e-8b6a-0b39d7c9d57e

	/// Room nights flagged as day-use (same-day arrival and departure, LOS_Nights = 0). Day-use handling governed under D-206.
	measure 'Day Use Room Nights' = CALCULATE ( [Room Nights], f_roomnights[IsDayUse] = TRUE () )
		formatString: #,##0
		displayFolder: 01 Volume
		lineageTag: 492379ec-f8ff-4009-9fba-360a6486c262

	/// Average LOS_Nights evaluated once per reservation, not per room-night row. Currently includes day-use reservations (LOS = 0), which lowers the result.
	measure 'Average Length of Stay' =
			AVERAGEX (
			    VALUES ( f_roomnights[ReservationID] ),
			    CALCULATE ( MAX ( f_roomnights[LOS_Nights] ) )
			)
		formatString: #,##0.00
		displayFolder: 02 Stay Behaviour
		lineageTag: 54518a53-0f4d-446a-b418-70df9f9014a5

	/// Average BookingWindowDays evaluated once per reservation. Source data contains negative values (minimum -1), meaning booking after arrival.
	measure 'Average Booking Window (Days)' =
			AVERAGEX (
			    VALUES ( f_roomnights[ReservationID] ),
			    CALCULATE ( MAX ( f_roomnights[BookingWindowDays] ) )
			)
		formatString: #,##0.0
		displayFolder: 02 Stay Behaviour
		lineageTag: 379e80fd-d3f0-45d7-b4b0-7d33c9668f80

	/// Reconciliation check. Should equal [Room Nights] because F_RoomNights is pre-filtered to inventory-deducting statuses at build time under D-208. Divergence indicates the build filter has changed.
	measure 'Inventory Deducting Room Nights' = CALCULATE ( [Room Nights], d_reservationstatus[InventoryDeduct] = TRUE () )
		formatString: #,##0
		displayFolder: 99 Diagnostics
		lineageTag: e835d085-d07b-4d8b-bded-9f3be6dfaa3e

	column RoomNightID
		dataType: string
		isHidden
		lineageTag: c6203c7c-ecaf-4ba3-92dd-7e04d5314851
		sourceLineageTag: RoomNightID
		summarizeBy: none
		sourceColumn: RoomNightID

		annotation SummarizationSetBy = Automatic

	column ReservationID
		dataType: string
		lineageTag: e880f550-6b17-4307-92e8-430df022bdc7
		sourceLineageTag: ReservationID
		summarizeBy: none
		sourceColumn: ReservationID

		annotation SummarizationSetBy = Automatic

	column PropertyKey
		dataType: string
		isHidden
		lineageTag: a36395c1-199f-46fd-820e-0ced884b6cbc
		sourceLineageTag: PropertyKey
		summarizeBy: none
		sourceColumn: PropertyKey

		annotation SummarizationSetBy = Automatic

	column PropertyID
		dataType: string
		isHidden
		lineageTag: 5202d825-b100-45ac-a6c8-f1ee787e4b1d
		sourceLineageTag: PropertyID
		summarizeBy: none
		sourceColumn: PropertyID

		annotation SummarizationSetBy = Automatic

	column StayDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e327df96-4ad3-4a01-9224-498ecc4d95c2
		sourceLineageTag: StayDate
		summarizeBy: none
		sourceColumn: StayDate

		annotation SummarizationSetBy = Automatic

	column SnapshotDateTime
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 6b4d325d-3fec-4cb6-babd-9d5afb06274d
		sourceLineageTag: SnapshotDateTime
		summarizeBy: none
		sourceColumn: SnapshotDateTime

		annotation SummarizationSetBy = Automatic

	column RoomTypeKey
		dataType: string
		isHidden
		lineageTag: 89c9e4b2-a036-4074-b513-17f344607665
		sourceLineageTag: RoomTypeKey
		summarizeBy: none
		sourceColumn: RoomTypeKey

		annotation SummarizationSetBy = Automatic

	column RatePlanKey
		dataType: string
		isHidden
		lineageTag: aea19927-c8f6-4431-9bea-067167208ed8
		sourceLineageTag: RatePlanKey
		summarizeBy: none
		sourceColumn: RatePlanKey

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: string
		isHidden
		lineageTag: 584da353-0d32-409c-83d0-a32a690c5c5e
		sourceLineageTag: ChannelKey
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column SegmentKey
		dataType: string
		isHidden
		lineageTag: 9c14b543-c188-4172-9166-f9dc7a45b56d
		sourceLineageTag: SegmentKey
		summarizeBy: none
		sourceColumn: SegmentKey

		annotation SummarizationSetBy = Automatic

	column ReservationStatusKey
		dataType: string
		isHidden
		lineageTag: 36bc9b4e-42a4-41ec-9790-3571b15af629
		sourceLineageTag: ReservationStatusKey
		summarizeBy: none
		sourceColumn: ReservationStatusKey

		annotation SummarizationSetBy = Automatic

	column MarketCountryKey
		dataType: string
		isHidden
		lineageTag: 5f5791ae-ff14-4104-ac6d-4f6f54a61c91
		sourceLineageTag: MarketCountryKey
		summarizeBy: none
		sourceColumn: MarketCountryKey

		annotation SummarizationSetBy = Automatic

	column BlockID
		dataType: string
		isHidden
		lineageTag: 3046dfa8-e05c-495b-923e-7810163dfc18
		sourceLineageTag: BlockID
		summarizeBy: none
		sourceColumn: BlockID

		annotation SummarizationSetBy = Automatic

	column EventID
		dataType: string
		isHidden
		lineageTag: c081ff9d-7a88-4b27-a387-7bd029c1e318
		sourceLineageTag: EventID
		summarizeBy: none
		sourceColumn: EventID

		annotation SummarizationSetBy = Automatic

	column IsGroupReservation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eb63f4e7-d020-44ec-b7be-d1f79caabee0
		sourceLineageTag: IsGroupReservation
		summarizeBy: none
		sourceColumn: IsGroupReservation

		annotation SummarizationSetBy = Automatic

	column BookingDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d651cc2-565c-480e-ae9c-6c23d2d80c81
		sourceLineageTag: BookingDateTime
		summarizeBy: none
		sourceColumn: BookingDateTime

		annotation SummarizationSetBy = Automatic

	column ArrivalDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 28ad16ae-122d-472d-b809-e6e968ebc47f
		sourceLineageTag: ArrivalDate
		summarizeBy: none
		sourceColumn: ArrivalDate

		annotation SummarizationSetBy = Automatic

	column DepartureDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 880e1abf-2ce7-47b2-99bf-0fbe85d7d7f5
		sourceLineageTag: DepartureDate
		summarizeBy: none
		sourceColumn: DepartureDate

		annotation SummarizationSetBy = Automatic

	column LOS_Nights
		dataType: int64
		formatString: 0
		lineageTag: fcca68f6-a30e-4f85-a2a7-bf4778f4b512
		sourceLineageTag: LOS_Nights
		summarizeBy: none
		sourceColumn: LOS_Nights

		annotation SummarizationSetBy = Automatic

	column BookingWindowDays
		dataType: int64
		formatString: 0
		lineageTag: 69de9664-acf5-419a-837e-356765ff1439
		sourceLineageTag: BookingWindowDays
		summarizeBy: none
		sourceColumn: BookingWindowDays

		annotation SummarizationSetBy = Automatic

	column CurrencyCode
		dataType: string
		isHidden
		lineageTag: 65532353-0b6a-4e9e-83d9-e4cdb42b8ac6
		sourceLineageTag: CurrencyCode
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column BookedRoomRevenue_RoomNight
		dataType: double
		isHidden
		lineageTag: 4d1d618a-7f75-418f-be55-21b78474c88b
		sourceLineageTag: BookedRoomRevenue_RoomNight
		summarizeBy: sum
		sourceColumn: BookedRoomRevenue_RoomNight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealizedRoomRevenue_RoomNight
		dataType: double
		isHidden
		lineageTag: e0d1886e-d1eb-400d-9a44-533a5087ab12
		sourceLineageTag: RealizedRoomRevenue_RoomNight
		summarizeBy: sum
		sourceColumn: RealizedRoomRevenue_RoomNight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RoomRevenue
		dataType: double
		isHidden
		lineageTag: 07ea86b7-5374-414a-9b2d-0e1d8fc83907
		sourceLineageTag: RoomRevenue
		summarizeBy: sum
		sourceColumn: RoomRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueState
		dataType: string
		isHidden
		lineageTag: 3f9cbe16-71f2-463e-bdd1-76540bbea550
		sourceLineageTag: RevenueState
		summarizeBy: none
		sourceColumn: RevenueState

		annotation SummarizationSetBy = Automatic

	column BookedRevenueDerivationMethod
		dataType: string
		isHidden
		lineageTag: decae884-d1e3-42ac-a686-274955957e03
		sourceLineageTag: BookedRevenueDerivationMethod
		summarizeBy: none
		sourceColumn: BookedRevenueDerivationMethod

		annotation SummarizationSetBy = Automatic

	column RealizedRevenueDerivationMethod
		dataType: string
		isHidden
		lineageTag: 056f5704-3fe1-4888-97b2-6a6726f365cd
		sourceLineageTag: RealizedRevenueDerivationMethod
		summarizeBy: none
		sourceColumn: RealizedRevenueDerivationMethod

		annotation SummarizationSetBy = Automatic

	column IsBlockPickupRoomNight
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c4a283c8-11f4-470d-a4ba-fa975974f7d2
		sourceLineageTag: IsBlockPickupRoomNight
		summarizeBy: none
		sourceColumn: IsBlockPickupRoomNight

		annotation SummarizationSetBy = Automatic

	column IsLatestCurrent
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9daccbaa-a3c4-4e0f-a369-fa8b52752e8a
		sourceLineageTag: IsLatestCurrent
		summarizeBy: none
		sourceColumn: IsLatestCurrent

		annotation SummarizationSetBy = Automatic

	column RevenueStreamKey
		dataType: string
		isHidden
		lineageTag: c916bee2-51d2-4657-bb42-39583de5808a
		sourceLineageTag: RevenueStreamKey
		summarizeBy: none
		sourceColumn: RevenueStreamKey

		annotation SummarizationSetBy = Automatic

	column TenantKey
		dataType: string
		isHidden
		lineageTag: e4333c1f-5461-4402-8a0b-56de40b0637b
		sourceLineageTag: TenantKey
		summarizeBy: none
		sourceColumn: TenantKey

		annotation SummarizationSetBy = Automatic

	column TenantID
		dataType: string
		isHidden
		lineageTag: de6aa0d4-7582-46e6-bd18-c9f36caaa66a
		sourceLineageTag: TenantID
		summarizeBy: none
		sourceColumn: TenantID

		annotation SummarizationSetBy = Automatic

	column IsDayUse
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f5553445-fc77-4aa5-9604-e5afc87ed8bf
		sourceLineageTag: IsDayUse
		summarizeBy: none
		sourceColumn: IsDayUse

		annotation SummarizationSetBy = Automatic

	partition f_roomnights = entity
		mode: directLake
		source
			entityName: f_roomnights
			schemaName: dbo
			expressionSource: 'DirectLake - LH_Menja_BI_v1_Mews_DEV'

